In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_crop = pd.read_csv("../dataset/Crop_Yield_Test.csv")

In [4]:
df_crop.head()

,id,soil_ph,soil_moisture,avg_temperature,total_rainfall,fertilizer_amount,pesticide_usage,sunlight_hours,nitrogen_content,phosphorus_content,potassium_content,irrigation_frequency,crop_type,region,season,harvest_date,field_id
0,0,6.345910,45.168174,18.878330,402.879335,55.482636,9.868763,1965.143907,2.322380,1.454562,1.264197,4,Rice,South,Summer,2021-06-29,F0288
1,1,5.883224,18.481114,24.393752,1120.207408,217.295757,4.652121,2209.117515,2.498442,0.985981,1.792262,5,Soybean,East,Autumn,2021-04-28,F0083
2,2,6.773234,38.289133,11.834019,838.467434,285.188113,8.591166,2771.285499,1.227889,0.403052,1.888120,6,Rice,North,Spring,2021-05-10,F0073
3,3,8.061032,12.541429,17.721095,182.266981,175.279529,1.389547,1006.565841,2.102867,0.457953,0.640130,5,Wheat,West,Spring,2021-03-22,F0139
4,4,6.099932,26.539885,34.291265,346.149521,152.803952,6.020481,1797.104226,1.220834,0.798761,1.386482,3,Wheat,Central,Spring,2021-09-25,F0323

In [5]:
import pandas as pd

crop_df = pd.read_csv("../dataset/Crop_Yield_Test.csv")
faostat_df = pd.read_csv("../dataset/FAOSTAT_Crop_Production.csv")

print("Crop Yield Dataset:")
print(crop_df.columns.tolist())

print("\nFAOSTAT Dataset:")
print(faostat_df.columns.tolist())

Crop Yield Dataset:
['id', 'soil_ph', 'soil_moisture', 'avg_temperature', 'total_rainfall', 'fertilizer_amount', 'pesticide_usage', 'sunlight_hours', 'nitrogen_content', 'phosphorus_content', 'potassium_content', 'irrigation_frequency', 'crop_type', 'region', 'season', 'harvest_date', 'field_id']

FAOSTAT Dataset:
['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code', 'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag', 'Flag Description', 'Note']

In [6]:
import pandas as pd

crop_df = pd.read_csv("../dataset/Crop_Yield_Test.csv")
faostat_df = pd.read_csv("../dataset/FAOSTAT_Crop_Production.csv")

In [7]:
crop_df["Year"] = pd.to_datetime(crop_df["harvest_date"]).dt.year

In [8]:
crop_df["Year"].value_counts()

Year
2021    1200
Name: count, dtype: int64

In [9]:
faostat_df = faostat_df[faostat_df["Area"] == "India"]

In [10]:
faostat_wide = faostat_df.pivot_table(
    index=["Item", "Year"],
    columns="Element",
    values="Value",
    aggfunc="first"
).reset_index()

In [11]:
faostat_wide.head()

Element               Item  Year  Area harvested  Production   Yield
0        Almonds, in shell  2015         21000.0     10000.0   476.2
1        Almonds, in shell  2016         11685.0      7933.0   678.9
2        Almonds, in shell  2017         12075.0      7061.0   584.8
3        Almonds, in shell  2018         10584.0     13688.0  1293.3
4        Almonds, in shell  2019         10432.0     10967.0  1051.3

In [12]:
faostat_wide["Item"].unique()

<ArrowStringArray>
[                                                        'Almonds, in shell',
 'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw',
                                                                    'Apples',
                                                                  'Apricots',
                                                                'Areca nuts',
                                                                   'Bananas',
                                                                    'Barley',
                                                                'Beans, dry',
                                                                  'Cabbages',
                                              'Cantaloupes and other melons',
                                                       'Carrots and turnips',
                                                     'Cashew nuts, in shell',
                                                            'Cassava, fresh',
                                                          'Castor oil seeds',
                                                 'Cauliflowers and broccoli',
                                                                  'Cherries',
                                                           'Chick peas, dry',
              'Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw',
              'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)',
                                                               'Cocoa beans',
                                                        'Coconuts, in shell',
                                                             'Coffee, green',
                                                                 'Coir, raw',
                                                    'Cucumbers and gherkins',
                                                    'Eggplants (aubergines)',
                                                                      'Figs',
                                                               'Ginger, raw',
                                                                    'Grapes',
                                                              'Green garlic',
                                             'Groundnuts, excluding shelled',
                                                       'Jute, raw or retted',
                       'Kenaf, and other textile bast fibres, raw or retted',
                                                                'Kiwi fruit',
                                                          'Lemons and limes',
                                                              'Lentils, dry',
                                                       'Lettuce and chicory',
                                                                   'Linseed',
                                                              'Maize (corn)',
                                           'Mangoes, guavas and mangosteens',
                                                                    'Millet',
                                                    'Mushrooms and truffles',
                                           'Natural rubber in primary forms',
                                              'Nutmeg, mace, cardamoms, raw',
                                                                      'Okra',
                           'Onions and shallots, dry (excluding dehydrated)',
                                                                   'Oranges',
                                                        'Other beans, green',
                    'Other berries and fruits of the genus vaccinium n.e.c.',
                                                'Other citrus fruit, n.e.c.',
                                                      'Other fruits, n.e.c.',
                                                   'Other oil seeds, n.e.c.',
                         'Other stimulant, spice and aromatic crops, n.e.c.',
                                                        'Other stone fruits',
                                             'Other tropical fruits, n.e.c.',
                                            'Other vegetables, fresh n.e.c.',
                                                                   'Papayas',
                                                    'Peaches and nectarines',
                                                                     'Pears',
                                                                 'Peas, dry',
                                                               'Peas, green',
                                                  'Pepper (Piper spp.), raw',
                                                          'Pigeon peas, dry',
                                                                'Pineapples',
                                                           'Plums and sloes',
                                                   'Pomelos and grapefruits',
                                                                  'Potatoes',
                                               'Pumpkins, squash and gourds',
                                                        'Rape or colza seed',
                                                                      'Rice',
                                                            'Safflower seed',
                                                     'Seed cotton, unginned',
                                                               'Sesame seed',
                                                                   'Sorghum',
                                                                'Soya beans',
                                                              'Strawberries',
                                                                'Sugar cane',
                                                            'Sunflower seed',
                                                            'Sweet potatoes',
                                        'Tangerines, mandarins, clementines',
                                                                'Tea leaves',
                                                                  'Tomatoes',
                                                    'Unmanufactured tobacco',
                                                         'Walnuts, in shell',
                                                               'Watermelons',
                                                                     'Wheat',
                                                                      'Yams']
Length: 86, dtype: str

In [13]:
crop_df["crop_type"].unique()

<ArrowStringArray>
['Rice', 'Soybean', 'Wheat', 'Barley', 'Corn']
Length: 5, dtype: str

In [14]:
faostat_wide[
    faostat_wide["Item"].str.contains(
        "Rice|Soybean|Soybeans|Maize",
        case=False,
        na=False
    )
]["Item"].unique()

<ArrowStringArray>
['Maize (corn)', 'Rice']
Length: 2, dtype: str

In [15]:
faostat_wide[
    faostat_wide["Item"].str.contains(
        "soy|soya",
        case=False,
        na=False
    )
]["Item"].unique()

<ArrowStringArray>
['Soya beans']
Length: 1, dtype: str

In [16]:
crop_mapping = {
    "Rice": "Rice",
    "Soybean": "Soya beans",
    "Wheat": "Wheat",
    "Barley": "Barley",
    "Corn": "Maize (corn)"
}

crop_df["Item"] = crop_df["crop_type"].map(crop_mapping)

In [17]:
combined_df = pd.merge(
    crop_df,
    faostat_wide,
    on=["Item", "Year"],
    how="left"
)

In [18]:
combined_df.head()

,id,soil_ph,soil_moisture,avg_temperature,total_rainfall,fertilizer_amount,pesticide_usage,sunlight_hours,nitrogen_content,phosphorus_content,...,crop_type,region,season,harvest_date,field_id,Year,Item,Area harvested,Production,Yield
0,0,6.345910,45.168174,18.878330,402.879335,55.482636,9.868763,1965.143907,2.322380,1.454562,...,Rice,South,Summer,2021-06-29,F0288,2021,Rice,46449121.0,1.952414e+08,4203.3
1,1,5.883224,18.481114,24.393752,1120.207408,217.295757,4.652121,2209.117515,2.498442,0.985981,...,Soybean,East,Autumn,2021-04-28,F0083,2021,Soya beans,12146576.0,1.298672e+07,1069.2
2,2,6.773234,38.289133,11.834019,838.467434,285.188113,8.591166,2771.285499,1.227889,0.403052,...,Rice,North,Spring,2021-05-10,F0073,2021,Rice,46449121.0,1.952414e+08,4203.3
3,3,8.061032,12.541429,17.721095,182.266981,175.279529,1.389547,1006.565841,2.102867,0.457953,...,Wheat,West,Spring,2021-03-22,F0139,2021,Wheat,31125160.0,1.095865e+08,3520.8
4,4,6.099932,26.539885,34.291265,346.149521,152.803952,6.020481,1797.104226,1.220834,0.798761,...,Wheat,Central,Spring,2021-09-25,F0323,2021,Wheat,31125160.0,1.095865e+08,3520.8

In [19]:
combined_df[["crop_type", "Year", "Area harvested", "Production", "Yield"]].head(10)

  crop_type  Year  Area harvested    Production   Yield
0      Rice  2021      46449121.0  1.952414e+08  4203.3
1   Soybean  2021      12146576.0  1.298672e+07  1069.2
2      Rice  2021      46449121.0  1.952414e+08  4203.3
3     Wheat  2021      31125160.0  1.095865e+08  3520.8
4     Wheat  2021      31125160.0  1.095865e+08  3520.8
5      Rice  2021      46449121.0  1.952414e+08  4203.3
6    Barley  2021        592470.0  1.656340e+06  2795.7
7   Soybean  2021      12146576.0  1.298672e+07  1069.2
8   Soybean  2021      12146576.0  1.298672e+07  1069.2
9      Rice  2021      46449121.0  1.952414e+08  4203.3

In [20]:
combined_df[["Area harvested", "Production", "Yield"]].isna().sum()

Area harvested    0
Production        0
Yield             0
dtype: int64

In [21]:
combined_df.isnull().sum()

id                      0
soil_ph                 0
soil_moisture           0
avg_temperature         0
total_rainfall          0
fertilizer_amount       0
pesticide_usage         0
sunlight_hours          0
nitrogen_content        0
phosphorus_content      0
potassium_content       0
irrigation_frequency    0
crop_type               0
region                  0
season                  0
harvest_date            0
field_id                0
Year                    0
Item                    0
Area harvested          0
Production              0
Yield                   0
dtype: int64

In [22]:
combined_df.duplicated().sum()

np.int64(0)

In [23]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1200 non-null   int64
 1   soil_ph               1200 non-null   float64
 2   soil_moisture         1200 non-null   float64
 3   avg_temperature       1200 non-null   float64
 4   total_rainfall        1200 non-null   float64
 5   fertilizer_amount     1200 non-null   float64
 6   pesticide_usage       1200 non-null   float64
 7   sunlight_hours        1200 non-null   float64
 8   nitrogen_content      1200 non-null   float64
 9   phosphorus_content    1200 non-null   float64
 10  potassium_content     1200 non-null   float64
 11  irrigation_frequency  1200 non-null   int64
 12  crop_type             1200 non-null   str
 13  region                1200 non-null   str
 14  season                1200 non-null   str
 15  harvest_date          1200 non-null   str
 16  field_id              1200 non-null   str
 17  Year                  1200 non-null   int32
 18  Item                  1200 non-null   str
 19  Area harvested        1200 non-null   float64
 20  Production            1200 non-null   float64
 21  Yield                 1200 non-null   float64
dtypes: float64(13), int32(1), int64(2), str(6)
memory usage: 247.0 KB

In [24]:
combined_df.describe()

,id,soil_ph,soil_moisture,avg_temperature,total_rainfall,fertilizer_amount,pesticide_usage,sunlight_hours,nitrogen_content,phosphorus_content,potassium_content,irrigation_frequency,Year,Area harvested,Production,Yield
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.0,1.200000e+03,1.200000e+03,1200.00000
mean,599.500000,6.486399,29.903112,22.224601,656.937138,168.948586,7.393134,2002.226674,1.751486,0.841193,1.233377,3.445000,2021.0,2.024697e+07,7.137160e+07,2990.19975
std,346.554469,1.161420,11.600778,7.206323,321.129717,72.165879,4.392082,575.218388,0.731164,0.368943,0.435689,1.704229,0.0,1.659255e+07,7.315691e+07,1051.81337
min,0.000000,4.500047,10.002113,10.008254,100.337783,50.027558,0.013226,1000.360078,0.503572,0.200504,0.501885,1.000000,2021.0,5.924700e+05,1.656340e+06,1069.20000
25%,299.750000,5.467575,20.080985,16.006294,369.879444,103.686785,3.433593,1513.584028,1.111761,0.530475,0.865218,2.000000,2021.0,9.921097e+06,1.298672e+07,2795.70000
50%,599.500000,6.468738,30.145237,22.134310,672.673478,165.617385,7.442773,1997.843163,1.722873,0.835470,1.206298,3.000000,2021.0,1.214658e+07,3.277241e+07,3303.30000
75%,899.250000,7.517364,40.107033,28.264939,926.226563,230.077816,11.084808,2500.632990,2.404878,1.151909,1.624206,5.000000,2021.0,3.112516e+07,1.095865e+08,3520.80000
max,1199.000000,8.498231,49.944457,34.998121,1199.621940,299.862631,14.982245,2999.781129,2.997893,1.499700,1.999577,6.000000,2021.0,4.644912e+07,1.952414e+08,4203.30000

In [25]:
combined_df.shape

(1200, 22)

In [26]:
combined_df["harvest_date"] = pd.to_datetime(combined_df["harvest_date"])
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1200 non-null   int64
 1   soil_ph               1200 non-null   float64
 2   soil_moisture         1200 non-null   float64
 3   avg_temperature       1200 non-null   float64
 4   total_rainfall        1200 non-null   float64
 5   fertilizer_amount     1200 non-null   float64
 6   pesticide_usage       1200 non-null   float64
 7   sunlight_hours        1200 non-null   float64
 8   nitrogen_content      1200 non-null   float64
 9   phosphorus_content    1200 non-null   float64
 10  potassium_content     1200 non-null   float64
 11  irrigation_frequency  1200 non-null   int64
 12  crop_type             1200 non-null   str
 13  region                1200 non-null   str
 14  season                1200 non-null   str
 15  harvest_date          1200 non-null   datetime64[us]
 16  field_id              1200 non-null   str
 17  Year                  1200 non-null   int32
 18  Item                  1200 non-null   str
 19  Area harvested        1200 non-null   float64
 20  Production            1200 non-null   float64
 21  Yield                 1200 non-null   float64
dtypes: datetime64[us](1), float64(13), int32(1), int64(2), str(5)
memory usage: 235.2 KB

In [27]:
combined_df = combined_df.rename(columns={
    "Area harvested": "area_harvested",
    "Production": "production",
    "Yield": "yield"
})
combined_df.columns

Index(['id', 'soil_ph', 'soil_moisture', 'avg_temperature', 'total_rainfall',
       'fertilizer_amount', 'pesticide_usage', 'sunlight_hours',
       'nitrogen_content', 'phosphorus_content', 'potassium_content',
       'irrigation_frequency', 'crop_type', 'region', 'season', 'harvest_date',
       'field_id', 'Year', 'Item', 'area_harvested', 'production', 'yield'],
      dtype='str')

In [28]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1200 non-null   int64
 1   soil_ph               1200 non-null   float64
 2   soil_moisture         1200 non-null   float64
 3   avg_temperature       1200 non-null   float64
 4   total_rainfall        1200 non-null   float64
 5   fertilizer_amount     1200 non-null   float64
 6   pesticide_usage       1200 non-null   float64
 7   sunlight_hours        1200 non-null   float64
 8   nitrogen_content      1200 non-null   float64
 9   phosphorus_content    1200 non-null   float64
 10  potassium_content     1200 non-null   float64
 11  irrigation_frequency  1200 non-null   int64
 12  crop_type             1200 non-null   str
 13  region                1200 non-null   str
 14  season                1200 non-null   str
 15  harvest_date          1200 non-null   datetime64[us]
 16  field_id              1200 non-null   str
 17  Year                  1200 non-null   int32
 18  Item                  1200 non-null   str
 19  area_harvested        1200 non-null   float64
 20  production            1200 non-null   float64
 21  yield                 1200 non-null   float64
dtypes: datetime64[us](1), float64(13), int32(1), int64(2), str(5)
memory usage: 235.2 KB

In [29]:
# Data Cleaning

# 1. Remove duplicate rows
combined_df = combined_df.drop_duplicates()

# 2. Convert harvest_date to datetime
combined_df["harvest_date"] = pd.to_datetime(
    combined_df["harvest_date"],
    errors="coerce"
)

# 3. Remove rows with invalid dates
combined_df = combined_df.dropna(subset=["harvest_date"])

# 4. Standardize categorical text
combined_df["crop_type"] = combined_df["crop_type"].str.strip()
combined_df["region"] = combined_df["region"].str.strip()
combined_df["season"] = combined_df["season"].str.strip()
combined_df["Item"] = combined_df["Item"].str.strip()
combined_df["field_id"] = combined_df["field_id"].str.strip()

# 5. Reset index after cleaning
combined_df = combined_df.reset_index(drop=True)

# 6. Display final shape
print("Cleaned dataset shape:", combined_df.shape)

# 7. Check missing values after cleaning
print("\nMissing values:")
print(combined_df.isnull().sum())

# 8. Check duplicates after cleaning
print("\nDuplicate rows:", combined_df.duplicated().sum())

Cleaned dataset shape: (1200, 22)

Missing values:
id                      0
soil_ph                 0
soil_moisture           0
avg_temperature         0
total_rainfall          0
fertilizer_amount       0
pesticide_usage         0
sunlight_hours          0
nitrogen_content        0
phosphorus_content      0
potassium_content       0
irrigation_frequency    0
crop_type               0
region                  0
season                  0
harvest_date            0
field_id                0
Year                    0
Item                    0
area_harvested          0
production              0
yield                   0
dtype: int64

Duplicate rows: 0

In [30]:
combined_df.to_csv("../dataset/Cleaned_Crop_Yield.csv", index=False)

In [31]:
combined_df.to_csv("../dataset/Cleaned_Crop_Yield.csv", index=False)